import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

const API = import.meta.env.VITE_API_URL || 'http://127.0.0.1:8000';
const SERVERS = ['east', 'west', 'europe'];
const NAV = [['dashboard','대시보드'],['market','시장'],['strategies','전략'],['portfolio','내 자산'],['insights','인사이트'],['settings','설정']];
const RANKS = [['profit','수익'],['roi','ROI'],['capital_efficiency','자본 효율'],['capital','필요 자본'],['risk','위험'],['confidence','신뢰도'],['freshness','신선도']];

const money = (v) => v == null || Number.isNaN(Number(v)) ? '—' : Number(v).toLocaleString();
const percent = (v) => v == null || Number.isNaN(Number(v)) ? '—' : `${Number(v).toFixed(2)}%`;
const text = (v, fallback = '—') => v == null || v === '' ? fallback : String(v);
const riskText = (v) => ({low:'낮음',medium:'보통',high:'높음',unknown:'미상'})[String(v || '').toLowerCase()] || text(v,'미상');
const freshnessText = (v) => ({fresh:'신선',recent:'최근',stale:'오래됨',insufficient:'데이터 부족'})[String(v || '').toLowerCase()] || text(v,'확인 불가');
const tone = (v) => ['high','fresh'].includes(String(v || '').toLowerCase()) ? 'good' : ['medium','recent'].includes(String(v || '').toLowerCase()) ? 'warn' : 'neutral';

function Icon({name}) {
  const p={dashboard:<><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>,market:<><path d="M4 19V9M10 19V5M16 19v-7M3 19h18"/></>,strategies:<><circle cx="6" cy="7" r="2"/><circle cx="18" cy="7" r="2"/><circle cx="12" cy="17" r="2"/><path d="m8 8.5 2.5 6.5M16 8.5l-2.5 6.5"/></>,portfolio:<><rect x="3" y="6" width="18" height="15" rx="2"/><path d="M8 6V4h8v2M3 11h18M15 15h3"/></>,insights:<><path d="M4 18h16M6 15l3-4 3 2 6-7M18 6h-4"/></>,settings:<><circle cx="12" cy="12" r="3"/><path d="M19 15.2a2 2 0 0 0 0-6.4M5 15.2a2 2 0 0 0 0-6.4M9 4.8a2 2 0 0 0 6 0M9 19.2a2 2 0 0 0 6 0"/></>,refresh:<><path d="M20 11a8 8 0 0 0-14.8-4L3 10M3 5v5h5M4 13a8 8 0 0 0 14.8 4L21 14M21 19v-5h-5"/></>,arrow:<><path d="M5 12h14m-6-6 6 6-6 6"/></>,close:<path d="m6 6 12 12M18 6 6 18"/>,chevron:<path d="m9 18 6-6-6-6"/>};
  return <svg className="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{p[name]}</svg>;
}
function Badge({children,tone='neutral'}){return <span className={`badge ${tone}`}>{children}</span>}
function Metric({label,value,accent=false}){return <div className="metric"><span>{label}</span><strong className={accent?'accent-value':''}>{value}</strong></div>}

function OpportunityCard({o,onOpen}){
  return <button className="opportunity-card" onClick={()=>onOpen(o)}><div className="opportunity-card-head"><div><Badge>{text(o.strategy_id)}</Badge><h3>{text(o.title,'기회')}</h3></div><Badge tone={tone(o.confidence)}>{text(o.confidence,'확인 불가')}</Badge></div><div className="route">{text(o.explanation,'실행 가능한 사업 기회')}</div><div className="opportunity-metrics"><Metric label="예상 수익" value={o.expected_profit==null?'Unknown':`+${money(o.expected_profit)} S`} accent={o.expected_profit!=null}/><Metric label="ROI" value={percent(o.roi_percent)}/><Metric label="필요 자본" value={`${money(o.required_capital)} S`}/><Metric label="시간당 수익" value={`${money(o.profit_per_hour)} S`}/></div><div className="opportunity-footer"><span>위험 {riskText(o.risk)}</span><span>유동성 {text(o.liquidity)}</span><span>데이터 {freshnessText(o.freshness)}</span><Icon name="chevron"/></div></button>;
}
function Drawer({o,close}){
  if(!o)return null;
  const rows=[['필요 자본',`${money(o.required_capital)} S`],['가용 자본',`${money(o.available_capital)} S`],['자본 활용률',percent(o.capital_utilization_percent)],['필요 수량',text(o.required_quantity)],['실행 가능 수량',text(o.executable_quantity)],['예상 매출',`${money(o.expected_revenue)} S`],['예상 비용',`${money(o.expected_cost)} S`],['예상 수익',o.expected_profit==null?'Unknown':`${money(o.expected_profit)} S`],['ROI',percent(o.roi_percent)],['시간당 수익',`${money(o.profit_per_hour)} S`],['위험',riskText(o.risk)],['유동성',text(o.liquidity)],['신뢰도',text(o.confidence)],['신선도',freshnessText(o.freshness)],['소요 시간',o.time_required==null?'—':`${Number(o.time_required).toFixed(1)} h`]];
  return <div className="drawer-backdrop" onClick={close}><aside className="drawer" onClick={e=>e.stopPropagation()}><button className="icon-button close" onClick={close} aria-label="닫기"><Icon name="close"/></button><Badge>{text(o.strategy_id)}</Badge><h2>{text(o.title)}</h2><p className="drawer-explanation">{text(o.explanation,'상세 설명이 없습니다.')}</p><div className="detail-grid">{rows.map(([a,b])=><Metric key={a} label={a} value={b}/>)}</div><div className="analysis-note"><strong>판단 근거</strong><p>{text(o.explanation,'데이터가 부족하여 추가 판단을 제공할 수 없습니다.')}</p></div></aside></div>;
}
function LineChart({rows}){
  const pts=(rows||[]).filter(x=>x.sell_price_min!=null).slice(-60);
  if(!pts.length)return <div className="chart-empty">차트에 사용할 데이터가 없습니다.</div>;
  const vals=pts.map(x=>Number(x.sell_price_min)), min=Math.min(...vals), max=Math.max(...vals), range=max-min||1;
  const line=vals.map((v,i)=>`${i/Math.max(vals.length-1,1)*100},${92-(v-min)/range*76}`).join(' ');
  return <div className="chart-wrap"><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="line-chart" aria-label="AODP 관측 가격 추세"><polyline points={line} fill="none" stroke="currentColor" vectorEffect="non-scaling-stroke" strokeWidth="1.5"/></svg></div>;
}
function Sidebar({page,setPage}){return <aside className="sidebar"><div className="brand"><div className="brand-mark">A</div><div><strong>ALBION</strong><span>MARKET HELPER</span></div></div><nav>{NAV.map(([id,label])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon name={id}/><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><div className="system-pill"><span className="live-dot"/> Market engine</div><small>Backend-driven analysis</small></div></aside>}
function Header({page,refreshing,refresh,profile}){return <header className="topbar"><div><span className="mobile-brand">ALBION</span><span className="breadcrumb">Business Intelligence / {NAV.find(x=>x[0]===page)?.[1]}</span></div><div className="top-actions"><button className="icon-button" onClick={refresh} disabled={refreshing} aria-label="새로고침"><Icon name="refresh"/></button><div className="profile-chip">{profile.avatar?<img className="avatar avatar-image" src={profile.avatar} alt="프로필"/>:<div className="avatar">{profile.name?.[0]?.toUpperCase()||'U'}</div>}<span>{profile.name||'사용자'}</span></div></div></header>}
function Filters({s,setS,capital,setCapital,risk,setRisk,strategy,setStrategy,sort,setSort,strategies,names}){return <section className="filter-bar"><label><span>서버</span><select value={s} onChange={e=>setS(e.target.value)}>{SERVERS.map(x=><option key={x} value={x}>{names[x]||x}</option>)}</select></label><label><span>가용 자본</span><div className="input-with-unit"><input type="number" min="0" value={capital} onChange={e=>setCapital(e.target.value)} placeholder="입력"/><em>S</em></div></label><label><span>위험</span><select value={risk} onChange={e=>setRisk(e.target.value)}><option value="">전체</option><option value="low">낮음</option><option value="medium">보통</option><option value="high">높음</option><option value="unknown">미상</option></select></label><label><span>전략</span><select value={strategy} onChange={e=>setStrategy(e.target.value)}><option value="">전체 전략</option>{strategies.map(x=><option key={x.strategy_id} value={x.strategy_id}>{x.name||x.strategy_id}</option>)}</select></label><label><span>정렬</span><select value={sort} onChange={e=>setSort(e.target.value)}>{RANKS.map(x=><option key={x[0]} value={x[0]}>{x[1]}</option>)}</select></label></section>}
function Dashboard({state,setPage,open}){
 const {server,setServer,names,capital,setCapital,risk,setRisk,strategy,setStrategy,sort,setSort,strategies,opportunities,loading,error}=state;
 const bestProfit=useMemo(()=>opportunities.reduce((b,o)=>o.expected_profit==null?b:b==null||o.expected_profit>b?o.expected_profit:b,null),[opportunities]); const bestRoi=useMemo(()=>opportunities.reduce((b,o)=>o.roi_percent==null?b:b==null||o.roi_percent>b?o.roi_percent:b,null),[opportunities]);
 return <div className="page"><div className="hero"><div><p className="eyebrow">ECONOMIC COMMAND CENTER</p><h1>오늘의 경제 기회</h1><p>현재 시장과 자본 조건을 기준으로 실행 가능한 사업 기회를 비교합니다.</p></div><Badge tone={opportunities.length?'good':'neutral'}>{loading?'데이터 확인 중':opportunities.length?'실행 기회 있음':'기회 없음'}</Badge></div><Filters {...{s:server,setS:setServer,capital,setCapital,risk,setRisk,strategy,setStrategy,sort,setSort,strategies,names}}/><div className="summary-strip"><Metric label="가용 자본" value={capital?`${money(capital)} S`:'미설정'}/><Metric label="등록 전략" value={strategies.length}/><Metric label="발견된 기회" value={opportunities.length}/><Metric label="최고 예상 수익" value={bestProfit==null?'Unknown':`+${money(bestProfit)} S`} accent={bestProfit!=null}/><Metric label="최고 ROI" value={percent(bestRoi)} accent={bestRoi!=null}/><Metric label="데이터 상태" value={opportunities.length?freshnessText(opportunities[0].freshness):'데이터 없음'}/></div>{error&&<div className="state-panel error-state"><strong>데이터를 불러오지 못했습니다.</strong><span>{error}</span></div>}<section className="section-block"><div className="section-title"><div><p className="eyebrow">RANKED BY {RANKS.find(x=>x[0]===sort)?.[1]?.toUpperCase()}</p><h2>오늘의 추천</h2></div><button className="text-button" onClick={()=>setPage('strategies')}>전략 탐색 <Icon name="arrow"/></button></div>{!loading&&!opportunities.length?<div className="state-panel"><strong>현재 추천할 기회가 없습니다.</strong><span>시장 데이터, 유동성 또는 레시피 데이터가 충분하지 않을 수 있습니다. 이는 수익이 0이라는 의미가 아닙니다.</span></div>:<div className="opportunity-grid">{opportunities.slice(0,6).map((o,i)=><OpportunityCard key={`${o.strategy_id}-${o.title}-${i}`} o={o} onOpen={open}/>)}</div>}</section><section className="split-section"><div className="panel"><div className="section-title"><div><p className="eyebrow">REGISTRY</p><h2>사업 전략</h2></div><button className="text-button" onClick={()=>setPage('strategies')}>전체 보기 <Icon name="arrow"/></button></div><div className="strategy-list">{strategies.map(x=><button className="strategy-row" key={x.strategy_id} onClick={()=>setPage('strategies')}><div className="strategy-symbol">{String(x.name||x.strategy_id).slice(0,1)}</div><div><strong>{text(x.name,x.strategy_id)}</strong><span>{text(x.description,'전략 설명 없음')}</span></div><Badge tone={x.calculator_key?'good':'neutral'}>{x.calculator_key?'사용 가능':'데이터 준비 중'}</Badge><Icon name="chevron"/></button>)}</div></div><div className="panel market-condition"><div className="section-title"><div><p className="eyebrow">MARKET STATUS</p><h2>시장 상태</h2></div></div><div className="condition-grid"><Metric label="서버" value={names[server]||server}/><Metric label="기회 데이터" value={opportunities.length?'사용 가능':'제한적'}/><Metric label="데이터 품질" value={opportunities.length?freshnessText(opportunities[0].freshness):'데이터 없음'}/><Metric label="유동성" value={opportunities.length?text(opportunities[0].liquidity):'확인 불가'}/></div><div className="market-note">가격·유동성 데이터가 부족한 경우 수익성 판단을 확정하지 않습니다.</div></div></section></div>;
}
function Market({market,setMarket,server}){return <div className="page"><div className="page-heading"><div><p className="eyebrow">MARKET INTELLIGENCE</p><h1>시장 분석</h1><p>아이템별 현재 가격, 추세와 도시 간 가격 차이를 확인합니다.</p></div></div><section className="market-search panel"><label><span>아이템 ID</span><input value={market.itemId} onChange={e=>setMarket({...market,itemId:e.target.value})} placeholder="아이템 ID"/></label><label><span>도시</span><input value={market.city} onChange={e=>setMarket({...market,city:e.target.value})} placeholder="도시"/></label><label><span>품질</span><input type="number" min="1" value={market.quality} onChange={e=>setMarket({...market,quality:e.target.value})}/></label><button className="primary-button" onClick={market.load}>분석</button></section>{market.error&&<div className="state-panel error-state">{market.error}</div>}{!market.itemId||!market.city?<div className="state-panel"><strong>아이템과 도시를 입력하세요.</strong><span>현재 backend가 제공하는 데이터만 표시합니다.</span></div>:<><div className="summary-strip market-summary"><Metric label="최저 판매가" value={money(market.current?.sell_price_min)}/><Metric label="최고 구매가" value={money(market.current?.buy_price_max)}/><Metric label="최근 가격" value={money(market.analysis?.statistics?.sell?.latest)}/><Metric label="평균 가격" value={money(market.analysis?.statistics?.sell?.average)}/><Metric label="가격 변화" value={market.analysis?.change?.sell?.percent==null?'—':percent(market.analysis.change.sell.percent)}/></div><section className="panel chart-panel"><div className="section-title"><div><p className="eyebrow">OBSERVED PRICE</p><h2>가격 추세</h2></div><Badge>AODP 관측 가격</Badge></div><div className="chart-tabs"><span className="active">라인</span><span className="disabled">캔들 · OHLC 데이터 없음</span></div><LineChart rows={market.analysis?.trend?.series||market.history}/><p className="chart-disclaimer">AODP 관측 가격을 시각화한 추세입니다. 체결 기반 거래소 캔들로 해석하지 않습니다.</p></section>{market.spread?.data_sufficient&&<section className="panel"><div className="section-title"><div><p className="eyebrow">CITY SPREAD</p><h2>도시 간 가격 차이</h2></div></div><div className="summary-strip"><Metric label="최저 도시" value={text(market.spread.spread.lowest_city)}/><Metric label="최고 도시" value={text(market.spread.spread.highest_city)}/><Metric label="절대 스프레드" value={money(market.spread.spread.absolute)}/><Metric label="스프레드" value={percent(market.spread.spread.percent)}/></div></section>}</>}</div>}
function Strategies({strategies}){return <div className="page"><div className="page-heading"><div><p className="eyebrow">STRATEGY EXPLORER</p><h1>사업 전략</h1><p>Registry에 등록된 전략만 표시합니다. 계산기가 없는 전략은 결과를 생성하지 않습니다.</p></div></div><div className="strategy-cards">{strategies.map(x=><article className="large-strategy-card" key={x.strategy_id}><div className="strategy-card-head"><div className="strategy-symbol large">{String(x.name||x.strategy_id).slice(0,1)}</div><Badge tone={x.calculator_key?'good':'neutral'}>{x.calculator_key?'사용 가능':'데이터 준비 중'}</Badge></div><h2>{text(x.name,x.strategy_id)}</h2><p>{text(x.description,'등록된 전략 설명이 없습니다.')}</p><div className="card-foot"><span>{text(x.category,'경제 활동')}</span><span>{x.calculator_key?'계산 가능':'메타데이터만 제공'}</span></div></article>)}</div></div>}
function Portfolio({profile,setProfile}){const [item,setItem]=useState(''),[qty,setQty]=useState('');const add=()=>{if(!item||!qty||Number(qty)<=0)return;setProfile({...profile,items:[...(profile.items||[]),{item,qty:Number(qty)}]});setItem('');setQty('')};return <div className="page"><div className="page-heading"><div><p className="eyebrow">PERSONAL ECONOMY</p><h1>내 자산</h1><p>게임 계정과 자동 동기화하지 않습니다. 직접 입력한 정보만 저장합니다.</p></div></div><section className="portfolio-grid"><div className="panel"><p className="eyebrow">LIQUID CAPITAL</p><h2>보유 Silver</h2><div className="big-number">{money(profile.silver)} <small>S</small></div><label className="form-row"><span>수정</span><input type="number" min="0" value={profile.silver} onChange={e=>setProfile({...profile,silver:e.target.value})}/></label></div><div className="panel"><p className="eyebrow">HOLDINGS</p><h2>보유 아이템</h2><div className="holding-form"><input value={item} onChange={e=>setItem(e.target.value)} placeholder="Item ID"/><input type="number" min="1" value={qty} onChange={e=>setQty(e.target.value)} placeholder="수량"/><button className="primary-button" onClick={add}>추가</button></div><div className="holding-list">{!(profile.items||[]).length?<span className="muted">등록된 보유 아이템이 없습니다.</span>:profile.items.map((x,i)=><div key={`${x.item}-${i}`}><span>{x.item}</span><strong>× {x.qty}</strong><button onClick={()=>setProfile({...profile,items:profile.items.filter((_,j)=>i!==j)})}>삭제</button></div>)}</div></div></section></div>}
function Insights({opportunities}){const usable=opportunities.filter(x=>x.expected_profit!=null);return <div className="page"><div className="page-heading"><div><p className="eyebrow">ANALYTICAL CONTEXT</p><h1>인사이트</h1><p>계산 엔진의 결과를 해석하기 위한 공간입니다. AI가 없는 상태에서는 임의의 분석을 생성하지 않습니다.</p></div></div><section className="insight-grid"><div className="panel insight-card"><div className="insight-icon">◎</div><h2>데이터 기반 판단</h2><p>{usable.length?`현재 ${usable.length}개의 기회에서 계산 가능한 수익 데이터가 확인됩니다.`:'현재 수익을 계산할 수 있는 충분한 기회 데이터가 없습니다.'}</p></div><div className="panel insight-card"><div className="insight-icon">◇</div><h2>불확실성 우선 표시</h2><p>가격 데이터만으로 주문 깊이나 실제 거래량을 추정하지 않습니다. 확인되지 않은 값은 Unknown 또는 Unavailable로 유지합니다.</p></div></section></div>}
function Settings({profile,setProfile,names}){return <div className="page"><div className="page-heading"><div><p className="eyebrow">PREFERENCES</p><h1>설정</h1><p>개인 프로필과 경제 분석 기본값을 관리합니다.</p></div></div><section className="settings-grid"><div className="panel"><p className="eyebrow">PROFILE</p><h2>프로필</h2><label className="form-row"><span>표시 이름</span><input value={profile.name} onChange={e=>setProfile({...profile,name:e.target.value})}/></label><label className="form-row"><span>프로필 이미지 URL</span><input value={profile.avatar||''} onChange={e=>setProfile({...profile,avatar:e.target.value})} placeholder="선택 사항"/></label><p className="muted">설정은 이 브라우저의 localStorage에 저장됩니다.</p></div><div className="panel"><p className="eyebrow">ECONOMY</p><h2>경제 설정</h2><label className="form-row"><span>주요 서버</span><select value={profile.server} onChange={e=>setProfile({...profile,server:e.target.value})}>{SERVERS.map(x=><option key={x} value={x}>{names[x]||x}</option>)}</select></label><label className="form-row"><span>최소 ROI</span><input type="number" value={profile.minRoi} onChange={e=>setProfile({...profile,minRoi:e.target.value})}/></label><label className="form-row"><span>최소 수익</span><input type="number" value={profile.minProfit} onChange={e=>setProfile({...profile,minProfit:e.target.value})}/></label><label className="form-row"><span>위험 선호</span><select value={profile.risk} onChange={e=>setProfile({...profile,risk:e.target.value})}><option value="">전체</option><option value="low">낮음</option><option value="medium">보통</option><option value="high">높음</option></select></label></div></section></div>}

function App(){
 const [page,setPage]=useState('dashboard'),[server,setServer]=useState('east'),[names,setNames]=useState({}),[capital,setCapital]=useState(''),[risk,setRisk]=useState(''),[strategy,setStrategy]=useState(''),[sort,setSort]=useState('profit');
 const [strategies,setStrategies]=useState([]),[opportunities,setOpportunities]=useState([]),[loading,setLoading]=useState(false),[error,setError]=useState(''),[selected,setSelected]=useState(null);
 const [profile,setProfileState]=useState(()=>{try{return JSON.parse(localStorage.getItem('amh-profile'))||{name:'',avatar:'',silver:'',items:[],server:'east',minRoi:'',minProfit:'',risk:''}}catch{return{name:'',avatar:'',silver:'',items:[],server:'east',minRoi:'',minProfit:'',risk:''}}}); const setProfile=x=>{setProfileState(x);localStorage.setItem('amh-profile',JSON.stringify(x))};
 const [market,setMarket]=useState({itemId:'',city:'',quality:1,current:null,analysis:null,spread:null,history:[],error:''});
 async function loadStrategies(){try{const r=await fetch(`${API}/api/strategies`);if(!r.ok)throw Error();setStrategies((await r.json()).strategies||[])}catch{setStrategies([])}}
 async function loadDashboard(){setLoading(true);try{const q=new URLSearchParams({server,sort,limit:'12'});if(capital)q.set('capital',capital);if(risk)q.set('risk',risk);if(strategy)q.set('strategy',strategy);const r=await fetch(`${API}/api/opportunities?${q}`);if(!r.ok)throw Error(`HTTP ${r.status}`);setOpportunities((await r.json()).opportunities||[]);setError('')}catch(e){setOpportunities([]);setError(e.message)}finally{setLoading(false)}}
 async function loadNames(){const a=await Promise.all(SERVERS.map(async id=>{try{const r=await fetch(`${API}/api/sources?server=${id}`);const d=r.ok?await r.json():{};return[id,d.server_name||id]}catch{return[id,id]}}));setNames(Object.fromEntries(a))}
 async function loadMarket(){if(!market.itemId||!market.city)return;try{const q=new URLSearchParams({item_id:market.itemId,city:market.city,quality:market.quality,server});const [a,b,c,d]=await Promise.all([fetch(`${API}/api/market/prices?${q}`),fetch(`${API}/api/market/analysis?${q}&range=24h`),fetch(`${API}/api/market/history?${q}`),fetch(`${API}/api/market/spread?item_id=${encodeURIComponent(market.itemId)}&quality=${market.quality}&server=${server}&range=24h`)]);if(!a.ok||!b.ok||!c.ok)throw Error('시장 API 요청에 실패했습니다.');setMarket(m=>({...m,current:(await a.json())[0],analysis:await b.json(),history:await c.json(),spread:d.ok?await d.json():null,error:''}))}catch(e){setMarket(m=>({...m,current:null,analysis:null,spread:null,history:[],error:e.message}))}}
 async function refresh(){await Promise.all([loadStrategies(),loadDashboard()]);if(page==='market')await loadMarket()}
 useEffect(()=>{loadNames();loadStrategies()},[]);useEffect(()=>{loadDashboard()},[server,capital,risk,strategy,sort]);
 const state={server,setServer,names,capital,setCapital,risk,setRisk,strategy,setStrategy,sort,setSort,strategies,opportunities,loading,error};
 let content=<Dashboard state={state} setPage={setPage} open={setSelected}/>; if(page==='market')content=<Market market={{...market,load:loadMarket}} setMarket={setMarket} server={server}/>; if(page==='strategies')content=<Strategies strategies={strategies}/>; if(page==='portfolio')content=<Portfolio profile={profile} setProfile={setProfile}/>; if(page==='insights')content=<Insights opportunities={opportunities}/>; if(page==='settings')content=<Settings profile={profile} setProfile={setProfile} names={names}/>;
 return <div className="app-shell"><Sidebar page={page} setPage={setPage}/><div className="main-shell"><Header page={page} refresh={refresh} refreshing={loading} profile={profile}/><main>{content}</main></div><Drawer o={selected} close={()=>setSelected(null)}/><nav className="mobile-nav">{NAV.slice(0,5).map(([id,label])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon name={id}/><span>{label}</span></button>)}</nav></div>;
}
createRoot(document.getElementById('root')).render(<App/>);
